### ISSUE TITLE
Strange latency spikes on 4.15.0-36 kernel

### ISSUE THREAD

**Issue by gtato** [alexei-led/pumba#103]
Pumba was working great until I got a new laptop with Ubuntu 18.04 and kernel 4.15.0-36.

Now if i try to emulate some latency (+-25ms) between the host and a container as follows:

`docker run --name pumba -d --rm -v /var/run/docker.sock:/var/run/docker.sock gaiaadm/pumba pumba netem --duration 24h30m --target 172.17.0.1  delay --time 25 --jitter 5  amazing_torvalds`

I get these ping results:
```
 ping 172.17.0.2
PING 172.17.0.2 (172.17.0.2) 56(84) bytes of data.
64 bytes from 172.17.0.2: icmp_seq=1 ttl=64 time=28.5 ms
64 bytes from 172.17.0.2: icmp_seq=4 ttl=64 time=29.8 ms
64 bytes from 172.17.0.2: icmp_seq=5 ttl=64 time=28.5 ms
64 bytes from 172.17.0.2: icmp_seq=2 ttl=64 time=4318 ms
64 bytes from 172.17.0.2: icmp_seq=3 ttl=64 time=4319 ms
64 bytes from 172.17.0.2: icmp_seq=8 ttl=64 time=28.0 ms
64 bytes from 172.17.0.2: icmp_seq=9 ttl=64 time=25.2 ms
64 bytes from 172.17.0.2: icmp_seq=10 ttl=64 time=27.1 ms
^C
--- 172.17.0.2 ping statistics ---
10 packets transmitted, 8 received, 20% packet loss, time 9064ms
rtt min/avg/max/mdev = 25.265/1100.755/4319.747/1858.235 ms, pipe 5
```

so for every 3-4 normal packets there are these spikes of 4 seconds. I am not sure if it is related to tc or the kernel itself.

**Comment by alexei-led** [comment]
@gtato strange, it should not be related to kernel.

I've checked with a basic alpine image (with `iproute2` package installed) and it works. 
Pumba does not do anything special besides running properly constructed `tc` commands.

**Comment by alexei-led** [comment]
4.14.70-72.55.amzn2.x86_64 on AWS
and my Macbook OSX

**Comment by alexei-led** [comment]
Take a look https://askubuntu.com/questions/1054540/netem-jitter-generation-problem

**Comment by alexei-led** [comment]
Seems to be a kernel issue, indeed.

**Comment by gtato** [comment]
So I updated to kernel 4.19.0 and everything works again. I guess you can close this issue. Thanks!

**Comment by alexei-led** [comment]
@gtato glad to hear, closing
