### ISSUE TITLE
when using --tc-image flag the sidekick image is not deleted after the command execution finishes

### ISSUE THREAD

**Issue by bmilescu** [alexei-led/pumba#106]
I'm sure if this is intended or not, but I think it could be a good idea to clean the sidekick image after the command is executed. As a workaround I am using something like this in order to clean the residual image:
**_sudo docker rm $(sudo docker ps -a -q -f ancestor=gaiadocker/iproute2)_**

**Comment by bmilescu** [comment]
duplicate of https://github.com/alexei-led/pumba/issues/97

**Comment by alexei-led** [comment]
@bmilescu hopefully will fix it soon
