### ISSUE TITLE
Regex issue with interface name

### ISSUE THREAD

**Issue by saikatprabhakar** [alexei-led/pumba#109]
~]# ./pumba_linux_amd64 netem -i enp6s0 -t <target_ip> --duration 1m delay --time 500

ERRO[0000] failed to construct Netem Delay Command       app=pumba error="bad network interface name: must match '[a-zA-Z]+[0-9]{0,2}'" function=github.com/alexei-led/pumba/pkg/chaos/netem.NewDelayCommand.func1 source="netem/delay.go:63"
FATA[0000] bad network interface name: must match '[a-zA-Z]+[0-9]{0,2}'  app=pumba function=main.main source="cmd/main.go:162"
 ~]#

Can we relax the interface name regex pattern to have alphanumeric characters anywhere ?

**Comment by alexei-led** [comment]
@saikatprabhakar sure. will try to embed this fix in next minor build. PR is welcome too.

**Comment by alexei-led** [comment]
#108 fixes this issue

**Comment by saikatprabhakar** [comment]
Thanks Alexei-Led/Pumba
