### ISSUE TITLE
Documentation doubts

### ISSUE THREAD

**Issue by dili91** [alexei-led/pumba#119]
Hello, a couple of things I noticed on the readme here: 

- --host global option required on Docker for Mac . not sure whether applies to recent version of docker. I am able to use pumba on mac without this option set. 
- --dry option on docu seems a typo. container is expecting a --dry-run option

**Comment by alexei-led** [comment]
@dili91 `--host` allows to connect to remote machine. `--dry` is an error  - will fix it. Thank you

**Comment by dili91** [comment]
> @dili91 `--host` allows to connect to remote machine. 

Sorry, I was referring to this line only on doc 

> Note: For Windows and OS X you will need to use --host argument, since there is no unix socket /var/run/docker.sock to mount.

**Comment by jjimenezroda** [comment]
I cannot make it work on Windows (with Docker for Windows Community edition).
the Container exists after 1 second with Exit code 3.
Is there something else I'm missing apart from the --host option?

**Comment by alexei-led** [comment]
@jjimenezroda I'm not using Windows, but have multiple users running `pumba` successfully on Windows. Probably, you need to enable Docker Remote API on Windows.
