### ISSUE TITLE
Slack hook certificate error

### ISSUE THREAD

**Issue by vsetka** [alexei-led/pumba#122]
Similar to #84, when I try to use the slack integration (`--slackhook https://hooks.slack.com/services/abc --slackchannel my-channel`), I get the following error:

> Failed to fire hook: Post https://hooks.slack.com/services/abc: x509: certificate signed by unknown authority.

I'm running the docker image **gaiaadm/pumba:0.6.2**.

**Comment by alexei-led** [comment]
@vsetka I think it related to missing `ca-certificates` package. Right now `gaiaadm/pumba` is a **SCRATCH** image (i.e. no OS packages, just single binary). In order to support CA there is a need to mount CA certificates into running containers from host machine

**Comment by vsetka** [comment]
@alexei-led thanks for the quick reply. I didn't see anything in the docs about this (it should be mentioned in the slack hook section at least, as hooks will over go over TLS).

So, if I mount the certs under `/etc/ssl/docker/`, it should work?

**Comment by alexei-led** [comment]
I will add certificates to the pumba docker image, soon. Meanwhile you can mount them to docker container
`/usr/share/ca-certificates` and  `/etc/ssl/certs`
