### ISSUE TITLE
Using re2 in pumba command in kubernetes template

### ISSUE THREAD

**Issue by LimeDang** [alexei-led/pumba#123]
When I run command:
`pumba pause --duration 5m delay --time 500 re2:.*my_container.*`
pumba can not search for my_container, as debugging I see string `re2:.*my_container.*` become one option of `delay`, not searching containers anymore.

When I run command:
`pumba pause --duration 5m re2:.*my_container.* delay --time 500`
pumba can not search for my_container also, as debugging I see string `delay --time 500` being appended to `re2:.*my_container.*`

Pumba can work only when running:
`pumba pause --duration 5m re2:.*my_container.*`

I expect all of them should work the same. Because with this issue I can not use option `delay` in `pause` or other commands and search for `re2:.*my_container.*`

**Comment by alexei-led** [comment]
@LimeDang you can run only single chaos command at time. `pause` is one command and `netem delay` is another. 

```
# add 3 seconds delay for all outgoing packets on device `eth0` (default) of `mydb` Docker container for 5 minutes
pumba netem --duration 5m delay --time 3000 mydb
```

```
# this command will pause main process (PID 1) within any .*my_container.* container for a 5 min
pumba pause --duration 5m re2:.*my_container.*
```
