### ISSUE TITLE
How to add more containers to kill

### ISSUE THREAD

**Issue by NikoHeikki** [alexei-led/pumba#124]
I have tried to ask this on gitter but havent got answer, how can I add more victims/containers to this string for killing more than 1 deploymentconfig called hello:

args: ["--random", "--log-level", "warning" , "--interval", "60s", "kill", "--signal", "SIGKILL", "re2:.*hello.*"]

like this:
args: ["--random", "--log-level", "warning" , "--interval", "60s", "kill", "--signal", "SIGKILL", "re2:.*hello.*" , "re2:.*hello2.*"]

**Comment by lazerion** [comment]
@NikoHeikki I am just also from community, but for `random` I can see that 
```
randomly select single matching container from list of target containers
```
Therefore, you may need to remove `random` option, other than that `re2` regex should do the multiple selection if it founds matches. Actually, you do or should not need more than one `re2` option passing.

**Comment by NikoHeikki** [comment]
@lazerion Hmm, but if I want for example pod "hello" and pod "anotherpod" to be both killed randomly in the interval 60s, how can I do this? I want to separate pods to be killed randomly.

**Comment by NikoHeikki** [comment]
Could someone smarter than me comment on this question. I am wondering why is the documentation so crap that I cannot specify basic usage and why is there a Gitter if nobody uses it, this is the most basic question.

**Comment by NikoHeikki** [comment]
Solution is with regular expression: args, this kills hello and ok pods randomly
 ["--random", "--log-level", "warning" , "--interval", "10s", "kill", "--signal", "SIGKILL", "re2:^(.*hello.*|.*ok.*)$"]
