### ISSUE TITLE
K8s & netem question

### ISSUE THREAD

**Issue by mariozel** [alexei-led/pumba#128]
Are the `netem` commands already available in current implementation on k8s? 
I've seen the pumba-kube.yml with an example to randomly kill containers but it's unclear if the netem commands are supported as well.

Thanks in advance.

By the way, this tool is super interesting and useful to have. Awesome work man.

**Comment by alexei-led** [comment]
@mariozel it's possible to use `netem` in k8s. `pumba` works with docker daemon directly and can inject container with `tc` on-board into any container network namespace on the same host.
