### ISSUE TITLE
pull-image can only be true

### ISSUE THREAD

**Issue by jhmartin** [alexei-led/pumba#132]
Pull-image is a command line argument, but evaluates to true whether omitted or passed.

Example:
```
./pumba -l debug netem -d 30s -t 8.8.8.8/32 --tc-image SNIP  rate --rate 100kbit re2:ecs
```
yields:

```
DEBU[0000] running netem command                         app=pumba duration=30s function=github.com/alexei-led/pumba/pkg/chaos/netem.runNetem id=b97b17957f45dcecf99be7e8eae5137a67820174609664499f70717cd335b8f0 iface=eth0 ips="[8.8.8.8/32]" name=/ecs-SNIP netem="[rate 100kbit]" pull=true source="netem/netem.go:23" tc-image="SNIP"
```

Note that `pull=true`
The same output occurs when passing --pull-image.

**Comment by alexei-led** [comment]
@jhmartin the default value for `--pull-image` is `true`. So, `pumba` tries to pull `tc` image to inject network emulation into target container. If you are using local image or do not wat to pull it you can specify `--pull-image=false`

**Comment by jhmartin** [comment]
Ah, might I suggest the docs be updated to indicate that? I had tried `--pull-image false` and received an error.
