### ISSUE TITLE
pumba wildcard not working properly

### ISSUE THREAD

**Issue by youbuntubelieveit** [alexei-led/pumba#133]
Hello, 

I am running ubuntu 16.04 in AWS. 
I was able to build the pumba docker image, but now i'm running into a problem while actually trying to kill containers pseudo-randomly. 

after spinning up a bunch of containers with similar prefixes
i run this command 

docker run -d -v /var/run/docker.sock:/var/run/docker.sock pumba kill --interval 10s --signal SIGTERM ^(prefix of containers)

but it will not kill the containers randomly after the specified amount of time. 

SOS please help a sinking ship

**Comment by jordandlaman** [comment]
I am getting the same behavior when trying to use the regex.  Though your command would kill all containers with that wildcard while I think you would want to pass the random flag as well as regex to filter down what it is looking at.

**Comment by alexei-led** [comment]
Probably, related to shell you are using. Use proper re2 regexp syntax and enclose expression in quotes.
