### ISSUE TITLE
regression: with --tc-image flag, iproute2 sidecar container is not deleted after the command execution finishes

### ISSUE THREAD

**Issue by dmurat** [alexei-led/pumba#135]
This feature works for version 0.6.1 and 0.6.2 but stopped at version 0.6.3. Maybe intentional, but probably regression.

**Comment by alexei-led** [comment]
Thank you, will check

**Comment by dmurat** [comment]
Just trying to get my head around GO source. Since this is my very first time that I'm looking in Go code, I might be very wrong. However, I've found this line in docker library 

https://github.com/moby/moby/blob/ad1b781e44fa1e44b9e654e5078929aec56aed66/client/container_create.go#L29

Since pumba is using version v1.13.1, if I'm correct, maybe this is a problem.

**Comment by alexei-led** [comment]
@dmurat thank you, will take a look and update lib if needed.

**Comment by alexei-led** [comment]
Downgraded to the previous Docker API version
