### ISSUE TITLE
Bug: netem command not working on minikube

### ISSUE THREAD

**Issue by LaumiH** [alexei-led/pumba#140]
I think the **pumba netem** command **does not work on minikube k8s clusters**. I noticed because I was using it to generate 100% network loss on a debian container and saw no effect at all.

My specs: minikube 1.5.2 with k8s 1.16.2 and docker 18.09.9, on an arch linux based distro. 

We already tested an older minikube version (minikube 1.2.0, docker 18.09.06, k8s 1.15.0). I also tried out to run it locally on my laptop on docker 19.03.5, also with a container pinging google, and this worked (100% network loss).

The deployment is [this one](https://github.com/LaumiH/k8sstuff/blob/master/test.yaml), I accessed the container with kubectl and did a simple ping. Then I deployed pumba:latest and pumba:0.4.8 with netem loss command on eth0. Any of them failed to stop the ping from going through.

The pumba kill, however, works. Debian has tc tool pre-installed.

Any ideas what to test or how to find out what is not working exactly? Will continue to test around a bit. I can provide logs if requsted.

**Comment by LaumiH** [comment]
I was also tested on a kubeadm based baremetal (packet) cluster with docker 18.06.3-ce and k8s 1.16.3 and there it works. minikube really seems to be the problem as far as I can see.

**Comment by alexei-led** [comment]
@LaumiH I never tested it on minikube. I think minikube is using Virtualbox VM under the hood. It looks like traffic control does not play nicely with Virtualbox. 
There is nothing I can do there.

**Comment by LaumiH** [comment]
Could we at least save people some time and add this restriction somewhere to the docs? There was someone else with this issue [here on Nov 14](https://gitter.im/pumba-chaos/Lobby), search for minikube.
