### ISSUE TITLE
Shortcomings invoking pumba programmatically

### ISSUE THREAD

**Issue by bittrance** [alexei-led/pumba#145]
I'm trying to write an extension for Chaos Toolkit for Docker Swarm, and leveraging pumba seemed like a quick way to support several failure modes. However, using pumba programmatically turns out to be tricky, for two reasons:

- `pumba <cmd> containers` does not accept container ID(s), only name(s). In my context, the caller has already decided on an exact container to harass and so the ID is the natural identifier.
- trying to ask pumba to kill containers it cannot find results is treated as a warning condition (log level warn, exit code 0), which seems strange given that it has been given instruction to kill containers and failed.

My interpretation is that programmatic usage is a core use case for pumba (slack hooks, JSON log output) but these two issues make it hard to be sure that the invocation was successful. Is there a reason for these behaviors?

**Comment by alexei-led** [comment]
@bittrance supporting ID is something that could be added. 

Currently `pumba` is designed as CLI tool, that should be executed on every Docker host, either manually with deployment tools (DaemonSet for K8s, for example). The idea is that once it's started it does not require too much handling: it's just there and injecting specified failures. Once you are done, stop it (or remove DaemonSet). App monitoring tools are supposed to detect falures and inspect how does app recover.

**Comment by bittrance** [comment]
It turns out the requirement to use names is ledd of an issue in practice as most API calls take names as well as IDs. The second issue is more of a problem. Would you accept a PR which `exit 1` in relevant cases where there are zero matching containers?

**Comment by alexei-led** [comment]
@bittrance I can consider PR
