### ISSUE TITLE
Anyway to run this on a Raspberry PI

### ISSUE THREAD

**Issue by macadech** [alexei-led/pumba#146]
The tool is exactly what I am looking for, but there doesn't appear to be any support for Raspberry PIs. I even tried running it within docker, but that fails too, presumably because the command doesn't support ARM architecture.
Is there a way to run the tool directly on a PI or remotely from a Linux or Mac ?

**Comment by alexei-led** [comment]
It can be compiled to ARM architecture. 
Never tried it, have no Raspberry

**Comment by alexei-led** [comment]
I will, probably, compile it also for Rasbery PI architecture, in next release.

**Comment by macadech** [comment]
Thanks Alexi. I can confirm it worked perfectly when I compiled it on a Raspberry PI 4.
Do you want me to close this issue ?

**Comment by alexei-led** [comment]
I will keep it open: till adding `arm64/linux` binary to release and then close. 
Thank you for testing!

**Comment by alexei-led** [comment]
fixed in release 0.7.0
