### ISSUE TITLE
Error when running 'pumba stress'

### ISSUE THREAD

**Issue by macadech** [alexei-led/pumba#149]
Hi, I am trying to run the following against a simple container which is just doing a ping to goolge.com ....
pumba stress --duration=5m --stressors "---cpu 4 --io 2 --vm 1 --vm-bytes 1G" tryme
which reports the following messages ...

ERRO[0020] failed to run stress-ng  app=pumba error="stress-ng exited with code: 1" function=github.com/alexei-led/pumba/pkg/container.dockerClient.stressContainerCommand source="container/client.go:638"
ERRO[0020] failed to stress container app=pumba error="stress-ng exited with code: 1" function="github.com/alexei-led/pumba/pkg/chaos/stress.(*StressCommand).Run" source="stress/stress.go:95"

pumba --version
Pumba version 0.7.1 - f874fdc (master) 2020-02-10_19:06_GMT

Am I doing something wrong ?

**Comment by alexei-led** [comment]
@macadech `---cpu 4 --io 2 --vm 1 --vm-bytes 1G` remove first `-` character

**Comment by alexei-led** [comment]
@macadech probably I need to somehow get exact error from `stress-ng` tool into logs

**Comment by macadech** [comment]
Not sure if helps, but here is the output after setting the log level to debug ...
pumba stress --duration=5m --stressors "---cpu 4 --io 2 --vm 1 --vm-bytes 1G" tryme
DEBU[0000] using names                                   app=pumba function=github.com/alexei-led/pumba/pkg/chaos.GetNamesOrPattern names="[tryme]" source="chaos/command.go:47"
DEBU[0000] no interval specified, running only once      app=pumba function=github.com/alexei-led/pumba/pkg/util.GetIntervalValue source="util/util.go:26"
DEBU[0000] no interval specified, running only once      app=pumba function=github.com/alexei-led/pumba/pkg/util.GetIntervalValue source="util/util.go:26"
DEBU[0000] stress testing all matching containers        app=pumba function="github.com/alexei-led/pumba/pkg/chaos/stress.(*StressCommand).Run" source="stress/stress.go:55"
DEBU[0000] listing matching containers                   app=pumba duration=5m0s function="github.com/alexei-led/pumba/pkg/chaos/stress.(*StressCommand).Run" labels="[]" limit=0 names="[tryme]" pattern= source="stress/stress.go:63" stressors="[---cpu 4 --io 2 --vm 1 --vm-bytes 1G]"
DEBU[0000] listing containers                            app=pumba function=github.com/alexei-led/pumba/pkg/container.dockerClient.listContainers source="container/client.go:90"
DEBU[0000] found container                               app=pumba function=github.com/alexei-led/pumba/pkg/container.dockerClient.listContainers id=6049e7eb2c0453aff6ed4b1ac1f4ff5a3c42e7d076261db5306ebd99f516a548 name=/tryme source="container/client.go:106"
DEBU[0000] stress testing container for duration         app=pumba container=6049e7eb2c0453aff6ed4b1ac1f4ff5a3c42e7d076261db5306ebd99f516a548 duration=5m0s function="github.com/alexei-led/pumba/pkg/chaos/stress.(*StressCommand).Run" pull image=true source="stress/stress.go:92" stress-ng image="alexeiled/stress-ng:latest-ubuntu" stressors="[---cpu 4 --io 2 --vm 1 --vm-bytes 1G]"
INFO[0000] stress testing container                      app=pumba dryrun=false function=github.com/alexei-led/pumba/pkg/container.dockerClient.StressContainer id=6049e7eb2c0453aff6ed4b1ac1f4ff5a3c42e7d076261db5306ebd99f516a548 name=/tryme source="container/client.go:302"
DEBU[0000] executing stress-ng command                   app=pumba function=github.com/alexei-led/pumba/pkg/container.dockerClient.stressContainerCommand image="alexeiled/stress-ng:latest-ubuntu" source="container/client.go:559"
DEBU[0000] pulling stress-ng image                       app=pumba function=github.com/alexei-led/pumba/pkg/container.dockerClient.stressContainerCommand image="alexeiled/stress-ng:latest-ubuntu" source="container/client.go:594"
DEBU[0000] &{Pulling from alexeiled/stress-ng   {0 0}}   app=pumba function=github.com/alexei-led/pumba/pkg/container.dockerClient.stressContainerCommand source="container/client.go:610"
DEBU[0000] &{Digest: sha256:da1ead7d5fdba2c1c299fd0c1f9c98169e8690ce9cd2b0eb9be5d8d163c9a088   {0 0}}  app=pumba function=github.com/alexei-led/pumba/pkg/container.dockerClient.stressContainerCommand source="container/client.go:610"
DEBU[0000] &{Status: Image is up to date for alexeiled/stress-ng:latest-ubuntu   {0 0}}  app=pumba function=github.com/alexei-led/pumba/pkg/container.dockerClient.stressContainerCommand source="container/client.go:610"
DEBU[0000] creating stress-ng container                  app=pumba function=github.com/alexei-led/pumba/pkg/container.dockerClient.stressContainerCommand image="alexeiled/stress-ng:latest-ubuntu" source="container/client.go:614"
DEBU[0005] stress-ng container created, starting it      app=pumba function=github.com/alexei-led/pumba/pkg/container.dockerClient.stressContainerCommand id=921433a6c7b43aebf3618bdf9009dcd73a2515817d0b83ef281f5c618c8937d2 source="container/client.go:621"
ERRO[0009] failed to run stress-ng                       app=pumba error="stress-ng exited with code: 1" function=github.com/alexei-led/pumba/pkg/container.dockerClient.stressContainerCommand source="container/client.go:638"
ERRO[0009] failed to stress container                    app=pumba error="stress-ng exited with code: 1" function="github.com/alexei-led/pumba/pkg/chaos/stress.(*StressCommand).Run" source="stress/stress.go:95"

NOTE: I am running this on a PI (armv71) will this make a difference ?

**Comment by alexei-led** [comment]
@macadech just fix `stressor` - `-` obsolete character

**Comment by macadech** [comment]
getting same issue even when run with ...
pumba stress -d 5m tryme

**Comment by macadech** [comment]
Hi Alexei,

Can you please reopen the issue as I get the same errors when I run ...

pumba stress -d 5m tryme

Regards,
Andy
Andy Robinson
Cloud Implementation Services - Certified Senior Cloud Managing Consultant
IBM Cloud Software
416 522 1786 (phone)

**Comment by alexei-led** [comment]
@macadech ok, will check. Ans sorry, it a very new feature - need to improve stability and error reporting. Consider it "experimental" :)

**Comment by alexei-led** [comment]
@macadech and I think it's related to PI also. Singe pumba uses Docker with `stress-ng` to inject it into a target container `cgroup`. But this image is `amd64` architecture. 
You can provide your own image with stress-ng compiled for arm64. There is a paragraph in README what is required from such image.

**Comment by macadech** [comment]
Thanks Alexei, really appreciate the effort you are putting into this.
The 'stress' option was perfectly timed as I am in the process of trying to test various scenarios that may arise.
I will look into creating a new container for the stress-ng.
Please keep up the fantastic work.
