### ISSUE TITLE
Why use a DaemonSet in Kubernetes?

### ISSUE THREAD

**Issue by mzeljkovic** [alexei-led/pumba#150]
Hi There,

Just curious why use a DaemonSet in Kubernetes. DaemonSet restarts the pumba pods once they complete. If you have a requirement to run a single/once off chaos test e.g. add 300ms delay for 5mins to container x, this means that after 5mins the pod will complete and will then be restarted by the DaemonSet, making it impossible to run a single/once off test.

So I guess there are 2 questions here:
1. Why use a DaemonSet?
2. Is there a way to avoid the scenario above? i.e. run the pod once and only once

Thanks in advance

**Comment by alexei-led** [comment]
@mzeljkovic there is a point in what you say. I'm thinking to make it a more K8s-friendly.
Currently, DaemonSet deployment does not suit your use case. Probably, you could use K8s Job with `nodeSelector` running it on specified nodes.

**Comment by mzeljkovic** [comment]
Thanks a million for the quick response @alexei-led
