### ISSUE TITLE
How to use Pumba on AWS Fargate Containers

### ISSUE THREAD

**Issue by balajipothula** [alexei-led/pumba#154]
How can I use Pumba on AWS Fargate Containers?

**Comment by alexei-led** [comment]
Unfortunately, Fargate does not support running privileged containers and does not allow to access the underlying Docker engine.

**Comment by balajipothula** [comment]
> Unfortunately, Fargate does not support running privileged containers and does not allow to access the underlying Docker engine.

Thank you so much for a quick reply. Its really really a quick reply.
