### ISSUE TITLE
NetEm multiple targets ip's leads to fatal execption, unrecognized CIDR

### ISSUE THREAD

**Issue by Babbleshack** [alexei-led/pumba#158]
When selecting multiple targets Pumba throws exception about invalid CIDR

## Command
`./pumba --log-level=debug --interval=601s netem --target="1.1.1.1/32,8.8.8.8/32" \
  --tc-image=gaiadocker/iproute2 --duration=600s delay --time=3000 --jitter=20 \
  "k8s_yarn-master_yarn-master-0_yarn-subcluster-a_475f0799-27f4-4ed0-b230-b307818c377c_0`

## Error
`FATA[0000] invalid CIDR address: 1.1.1.1/32,8.8.8.8/32 `

**Comment by Babbleshack** [comment]
This happens because IP strings are not properly parsed. 

DelayCommand is initialized with a string containing separator. 

Seems a library is used for parsing command line args, so I will leave this here until I have a chance to look at that.
```
// pkg/chaos/netem/delay.go:79-85
	// validate ips
	var ips []*net.IPNet
	for _, str := range strings.split(ipsList[0], ",") {
		ip, err := util.ParseCIDR(str)
		if err != nil {
			return nil, err
		}
		ips = append(ips, ip)
	}
```

**Comment by alexei-led** [comment]
@Babbleshack you should pass multiple IPs not as comma separated but as multiple target options

```
./pumba --log-level=debug --interval=601s netem \
     --target=1.1.1.1/32 --target=8.8.8.8/32 \ 
     --tc-image=gaiadocker/iproute2 --duration=600s delay --time=3000 --jitter=20 \
     "k8s_yarn-master_yarn-master-0_yarn-subcluster-a_475f0799-27f4-4ed0-b230-b307818c377c_0
```

and, by the way, you can use labels to select K8s pods

```
./pumba --log-level=debug --interval=601s netem \
     --target=1.1.1.1/32 --target=8.8.8.8/32 \ 
     --tc-image=gaiadocker/iproute2 --duration=600s delay --time=3000 --jitter=20 \
     --label=io.kubernetes.pod.name=<POD_NAME> \
     --label=io.kubernetes.pod.namespace=<NAMESPACE>
```

**Comment by Babbleshack** [comment]
Thanks! 

The README mention IP's should be separated by comma's
```
   --target value, -t value     target IP filter; comma separated. netem will impact only on traffic to target IP(s)
```

I thought this might be an issue with urfavecli's StringSliceFlag type, however I couldn't find documentation describing its intended behavior.
