### ISSUE TITLE
TC not found or failed

### ISSUE THREAD

**Issue by Asgoret** [alexei-led/pumba#159]
Hi! 

Environment:

- OS:

```
CentOS Linux release 7.7.1908 (Core)
```
- Kernel:
```
3.10.0-1062.4.1.el7.x86_64
```
- Docker version:
```
Client:
 Version:         1.13.1
 API version:     1.26
 Package version: docker-1.13.1-103.git7f2769b.el7.centos.x86_64
 Go version:      go1.10.3
 Git commit:      7f2769b/1.13.1
 Built:           Sun Sep 15 14:06:47 2019
 OS/Arch:         linux/amd64

Server:
 Version:         1.13.1
 API version:     1.26 (minimum version 1.12)
 Package version: docker-1.13.1-103.git7f2769b.el7.centos.x86_64
 Go version:      go1.10.3
 Git commit:      7f2769b/1.13.1
 Built:           Sun Sep 15 14:06:47 2019
 OS/Arch:         linux/amd64
 Experimental:    false
```
- Kubernetes:
```
v1.11.0+d4cacc0
```
- OKD (Community version of openshift):
```
v3.11.0+0731b2f-347
```

Description:

When I try to use pumba on some containers (which have tc inside) pumba show errors that there is no `tc command` or command failed and log in the manual for debugging. When I exec inside container manual all works fine. I find some information, which can help. When I exec inside the container I'm `root` user. So, how can I saw which user pumba tried to use?

**Comment by Asgoret** [comment]
@alexei-led can you help plz?

**Comment by alexei-led** [comment]
##@Asgoret Hey, `pumba` is running `tc` in container with`docker exec` command, so I think you can try to find out what is the user name with `id -u -n`

**Comment by Asgoret** [comment]
@alexei-led don't understand you correctly... I wrote `./pumba netem --duration 5m corrupt --percent 10 <container name>` and...where add `id -u -n`?

**Comment by alexei-led** [comment]
@Asgoret I just want you to run `docker exec -it <container> id -u -n`. This should print container username.
You can also try run `docker exec -it <container> tc -help` and let me know if you can run tc command

**Comment by Asgoret** [comment]
@alexei-led 
It's running inside OKD, so there is no user inside, there is only `ID <some number>`
And yeah, if I run `exec tc -help` I see the help of tc

Sorry for long response  :(

**Comment by stromnet** [comment]
Make sure the `which` command exists in the image, I had an image which lacked it and it failed to find it, since it explicitly uses `which`: https://github.com/alexei-led/pumba/blob/82ae1c42c21a4975004af64abfa3c11c2bff9bbb/pkg/container/client.go#L658

**Comment by Asgoret** [comment]
@stromnet It in the image because I can use it when exec inside.

**Comment by alexei-led** [comment]
@Asgoret can you share your container (or similar) with commands to reproduce this issue.

**Comment by nishu88** [comment]
@Asgoret  
`yum install iproute` (this installs tc) ,did the trick for me, remember u need this installed inside the container you are trying to disrupt.

**Comment by alexei-led** [comment]
@Asgoret or use `tc-image` parameter, passing any Docker image with `tc` tool on-board.
