### ISSUE TITLE
Control the packet selection in loss/corruption/duplication commands

### ISSUE THREAD

**Issue by deanstef** [alexei-led/pumba#160]
Hi,

I am using puma for chaos testing in a network of several docker containers. Is there any way of injecting the puma commands `loss`, `corrupt` and `duplicate`, toward targeted packets without using any probability model (i.e. Bernoulli model).

Thank you

**Comment by alexei-led** [comment]
@deanstef `pumba` uses `tc` tool for network emulation. If no probability model is specified `tc` uses *Normal* distribution by default.
