### ISSUE TITLE
Unable to start Pumba docker container on MacOs

### ISSUE THREAD

**Issue by dipAch** [alexei-led/pumba#161]
Trying to setup **Pumba** docker environment on MacOS.

**Host Details:**

> OS -> macOS High Sierra
> Version -> 10.13.5

Documentation is unclear on what the value for the **--host** global option should be on MacOS.

Target docker instances are running Alpine Linux (Version **3.7+**).

Command being run & output received:
```
$> docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock \
   gaiaadm/pumba:master pumba --host <VALUE??> --interface eth0 --duration 1m delay \
   --time 3000 <TARGET_CONTAINER>
No help topic for 'pumba'
```

**Docker Details:**

> Engine -> 19.03.4

Can someone point me in the right direction?

**Comment by alexei-led** [comment]
@dipAch no need to provide the `host` option. Use it to connect to remote Docker host only.

**Comment by Cpaulyz** [comment]
I encountered similar problems.

> OS: Macos Monterey (m1)
> Docker: v20.10.13


I tried to setup pumba docker on MacOS but failed.
```
> docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock gaiaadm/pumba:0.9.0 pumba netem --interface eth0 --duration 1m delay --time 3000 tryme
No help topic for 'pumba'
```

However, pumba can be executed normaly with binaries(download from release page, using darwin/arm64 version).
```
./pumba netem --interface eth0 --duration 1m delay --time 3000 tryme
```

Can u help me plz? @alexei-led

**Comment by buffb** [comment]
In case anyone stumbles upon this, it seems crucial to remove the pumba from the command to run.
I got it working with `docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock gaiaadm/pumba  netem --interface eth0 --duration 1m delay --time 3000 tryme`
