### ISSUE TITLE
Error running Pumba on OpenShift version 4.3

### ISSUE THREAD

**Issue by Vijay5775** [alexei-led/pumba#169]
Hello Team,

Appreciate if you can help confirm if Pumba can run on OpenShift Container Platform version 4.3.19, running Kubernetes version 1.16.2 please? I've created Daemon Set, elevated privileges, edited SCC's but run into errors as below,

`error msg="failed to list containers" app=pumba error="Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/containers/json?limit=0: dial unix /var/run/docker.sock: connect: permission denied" function=github.com/alexei-led/pumba/pkg/container.dockerClient.listContainers source="container/client.go:90"`

I presume starting version 3.7, OpenShift uses CRI-O as opposed to Docker runtime? could it be due to this? or a permission issue somewhere please? many thanks.

**Comment by alexei-led** [comment]
@Vijay5775 Pumba works with Docker API only. It does not support other containers runtimes.
