### ISSUE TITLE
Build instructions are not correct for 0.7.4

### ISSUE THREAD

**Issue by oneEdoubleD** [alexei-led/pumba#170]
OS: Ubuntu 20.04
Docker: 19.03.12

1. The build instructions mention building with hack/build.sh however only hack/github-release.sh exists. 
2. `./hack/xbuild.sh` no longer exists for creating binaries
3. Docker fails to build because of Step 10, where `Step 10/48 : COPY go.* .` should be `Step 10/48 : COPY go.* ./` else you get an error `When using COPY with more than one source file, the destination must be a directory and end with a /`.
4. All build methods in 0.7.4 seem to require a GITHUB_TOKEN env, it'd be worth adding a line to the build docs on why this is the case. 

I ended up building 0.7.0 correctly.

**Comment by alexei-led** [comment]
@oneEdoubleD fixed it; both Docker build and command line (switched to Makefile)
