### ISSUE TITLE
pull-image by default may accidentally hit the Docker rate limit

### ISSUE THREAD

**Issue by gy1005** [alexei-led/pumba#188]
Docker has recently enforced a [rate limit policy ](https://www.docker.com/increase-rate-limits) for pulling images. Pulling images by default may result in unexpected rate-limiting by Docker Hub. Is there a specific reason for pull-image=true by default? If not, I would highly recommend reusing the local image by default, instead of pulling the images every time.

**Comment by alexei-led** [comment]
you can use different registries without limit and bake your image. closing.
