### ISSUE TITLE
"cgroup change of group failed" issue is seen while using stress-ng

### ISSUE THREAD

**Issue by avinashnarra** [alexei-led/pumba#189]
Hi @alexei-led ,

I am trying to use stress-ng by using your latest ubuntu image on K8s , but seeing below issue

"cgroup change of group failed"

Can you help me in resolving the issue.

I have all capabilities like SYS_ADMIN,NET_ADMIN.

**Comment by avinashnarra** [comment]
@alexei-led Help needed on the above issue

**Comment by alexei-led** [comment]
Closing, duplicate of #181

**Comment by denz0x13** [comment]
Hi @alexei-led 

Still have the same issue on Ubuntu 20.04. Using minikube v1.15.1
