### ISSUE TITLE
v0.7.7 tarball sha256 change?

### ISSUE THREAD

**Issue by carlocab** [alexei-led/pumba#190]
We're attempting to update Homebrew's version of Go (https://github.com/Homebrew/homebrew-core/pull/66355).

While testing the new version, CI produced the following error:
```
==> brew install --build-from-source pumba
==> FAILED
==> Downloading https://github.com/alexei-led/pumba/archive/0.7.7.tar.gz
==> Downloading from https://codeload.github.com/alexei-led/pumba/tar.gz/0.7.7
Error: SHA256 mismatch
Expected: 5da828d47d7d46305fc921445ad47d9825a1d54f09b8be8a01ff2095c804fe2d
  Actual: 16cba72910bc6d62ed394e5fdeaeb70ca916c925a4f0a83eea06359703de9aae
```

I can update the sha256 associated with pumba, but CI will come back to me with the following error:
```
pumba:
  * stable sha256 changed without the url/version also changing; please create an issue upstream to rule out malicious circumstances and to find out why the file changed.
```

Can I confirm that nothing is amiss here?

**Comment by arbourd** [comment]
@alexei-led would you be able to confirm if you re-released `0.7.7`? We just need it to fix pumba on Homebrew. 🙏

**Comment by alexei-led** [comment]
I released 0.7.7

**Comment by arbourd** [comment]
Thank you!

**Comment by carlocab** [comment]
Thank you for the clarification.
