### ISSUE TITLE
Issue with stress command

### ISSUE THREAD

**Issue by ZaHack** [alexei-led/pumba#191]
Just figuring out how to use this tool and all it’s functionality. I’m trying to run a stress test with a different stressor specification. I’m currently running: pumba stress -d 5s --stressors ”--cpu 5” mycontainer. It returns FATA[0000] flag provided but not defined: -cpu 5. I may have a miss understanding on how I’m supposed to use this functionality. It’s not super clear in the readme on how the syntax is supposed to be. So not sure if this is a bug or just plain user error. Thank you.

**Comment by ZaHack** [comment]
Figured it out by reading the scripts in examples

**Comment by ramgiteng** [comment]
@ZaHack , I am facing an issue myself. 

Error: one or more stress test failed: stress-ng failed with error

Did you experience the same error? Could you please explain to me how you got it working? Thanks!
