### ISSUE TITLE
Unable to generate binaries on Mac

### ISSUE THREAD

**Issue by svallepu** [alexei-led/pumba#192]
go version
go version go1.16 darwin/amd64

make 
go get golang.org/x/lint/golint
go get github.com/golangci/golangci-lint/cmd/golangci-lint@v1.33.0
go get github.com/axw/gocov/...
go get github.com/AlekSi/gocov-xml
go get github.com/tebeka/go2xunit
▶ running gofmt...
▶ running golint...
make: golint: No such file or directory
make: *** [lint] Error 1
--------

docker build -t pumba -f docker/Dockerfile .
Sending build context to Docker daemon  499.7kB
Error response from daemon: Dockerfile parse error line 26: Unknown flag: mount

**Comment by alexei-led** [comment]
@svallepu you need to use docker buildkit, check [here](https://docs.docker.com/develop/develop-images/build_enhancements/)
