### ISSUE TITLE
Contact services on a different host in docker swarm

### ISSUE THREAD

**Issue by astha-textiq** [alexei-led/pumba#194]
@alexei-led 
I have downloaded the image on one of the nodes of my docker swarm and I can kill the containers present on the same node.

`sudo docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock pumba --interval=10s --random --log-level=info kill --signal=SIGKILL "re2:^redis"`
However, some of my services are hosted on a different node in the docker swarm. The same command doesnt work for them. The documentation gives the parameter --host but I tried passing public, private ip addresses and it doesnt work either. I am pretty sure I am using it wrong.

Any suggestions on how to kill the services present on different nodes? I can scale them down to 0 and then 1 but that I can do without the tool itself.

**Comment by alexei-led** [comment]
@astha-textiq check if the remote port is open and not blocking access from IP you are running pumba. configure TLS if required (pumba support working with TLS)

**Comment by alexei-led** [comment]
no plans to support Docker swarm. Closing.
