### ISSUE TITLE
Persistent or "daemon" mode

### ISSUE THREAD

**Issue by sk2** [alexei-led/pumba#196]
Hi, awesome tool! I want to affect multiple links in a Containerlab (https://containerlab.srlinux.dev) network topology.
With the "duration" command, it appears I can only affect one at a time - as duration reverts the changes after the duration has completed.
Is it possible to run the pumba netem command that simply sets the tc parameters permanently? I can then later revert the changed manually by running the command again.

The CLI API for the tool is really nice to stitch all of the pieces together, so this would be preferable to doing all of the commands manually.
Thanks!

**Comment by alexei-led** [comment]
@sk2 the chaos impact is limited by design, either based on the `duration` value or when the `pumba` process exits. I have no plans to change this.
