### ISSUE TITLE
always the argument --pull-image is true

### ISSUE THREAD

**Issue by jitapichab** [alexei-led/pumba#203]
in the line `pull := c.Parent().BoolT("pull-image")` line: 79 of the file pkg/chaos/netem/cmd/delay.go the result of this param is allways true. 

for example:

withouth --pull-image
![image](https://user-images.githubusercontent.com/22335092/133504862-46951982-a7db-4be3-9625-d3e9f13d0254.png)

with --pull-image
![image](https://user-images.githubusercontent.com/22335092/133504959-dcc25ed9-4102-41b0-a665-80cf10650297.png)

you can observe that in the two cases **with --pull-image or withouth --pull-image** the **flag pull is true**, and the problem with this is the rate limits of docker.

Thanks a lot. :)

**Comment by jitapichab** [comment]
I created the pull request https://github.com/alexei-led/pumba/pull/204

**Comment by alexei-led** [comment]
@jitapichab you can pass `false` to the `pull-image` option, like this `--pull-image=false` (it's `true` if not passed)
