### ISSUE TITLE
Stress Feature Not Working

### ISSUE THREAD

**Issue by ramgiteng** [alexei-led/pumba#210]
Hello @alexei-led,

I am unable to execute the pumba stress command. I have 5 containers in my Docker and would like to attack the containers' cpu/ram. The following is the command for applying stress on one container and the corresponding output.

**Command**: sudo docker run -d --cap-add SYS_ADMIN -it --name=pumba -v /var/run/docker.sock:/var/run/docker.sock gaiaadm/pumba stress -d 10s <containerName>
**Output**: FATA[0002] one or more stress test failed: stress-ng failed with error: stress-ng exited with error: cgroup change of group failed

I also ran **docker container ls** and noticed that **alexeiled/stress-ng:latest-ubuntu** and **gaiaadm/pumba** images were up and running for a brief period of time before exiting.

**Details**:
**Linux Distros**: CentOS
**Docker version**: 1.13.1
**Pumba version**: 0.7.8

Can you please help me troubleshoot this issue?  Please let me know if you need any further details.

Thanks for the support!

**Comment by alexei-led** [comment]
will try to reproduce it

**Comment by ramgiteng** [comment]
Hi @alexei-led 
I was wondering if there has been any update on this. Also, how can we use pumba to attack the process within the container? For example: Inject CPU/RAM chaos into a Node or Java process running inside a docker container.
