### ISSUE TITLE
IO-Stress: bind source path does not exist

### ISSUE THREAD

**Issue by Vr00mm** [alexei-led/pumba#218]
Hello Everyone,

Iam trying to start an io stress from this command line:

```
pumba \
--host unix:///var/vcap/sys/run/docker/docker.sock
--log-level debug \
--label io.kubernetes.pod.name=release-name-test-deploy-f59f58c7-v5xvc \
stress \
--duration 120s \
--stressors \
--cpu 1 --io 4 --hdd 4 --hdd-bytes 10% --timeout 120s
```
I get this error:
Failed to create stress-ng container: Error response from daemon: invalid mount config for type \"bind\": bind source path does not exist: /var/run/docker.sock

From this line, the source socket is hardcoded:
https://github.com/alexei-led/pumba/blob/master/pkg/container/client.go#L677

Should it not use the DOCKER_HOST env variable or the --host command line arguments ?
Or I missed a configuration ?

Thanks for the help
Best regards

**Comment by alexei-led** [comment]
@Vr00mm You are right - this is bug. If you will commit a PR I will review and approve it.

**Comment by Vr00mm** [comment]
Thanx for reply @alexei-led, I pushed a PR proposal, do not hesitate to discuss on :)

Best regards
