### ISSUE TITLE
Netem Functionalities not working ?

### ISSUE THREAD

**Issue by saadmanfarhad** [alexei-led/pumba#221]
Hi, I've trying to follow the examples for `netem delay` and `netem loss`. I did exactly like the clips but it seems that the netem emulations are not working. I tried the container stop and kill commands which seems to work fine. Anybody else facing such issues ?

**Comment by alexei-led** [comment]
@saadmanfarhad, please describe a way to reproduce. 

OS Version, Docker version, commands you are running and errors.

**Comment by alexei-led** [comment]
Supporting containerd probably will be the next thing I will work on.
