### ISSUE TITLE
GHSA-77vh-xpmg-72qh: Clarify `mediaType` handling

### ISSUE THREAD

**Issue by KevinPoole** [alexei-led/pumba#225]
Anchore and Twistlock both identify Pumba as being vulnerable to Github Security Advisory https://github.com/advisories/GHSA-77vh-xpmg-72qh. 

Fix is described as upgrading github.com/opencontainers/image-spec  to at least 1.0.2.

-Kevin

**Comment by alexei-led** [comment]
fixed
