### ISSUE TITLE
`pumba --version` returned `[none:none] none` in 0.9.6

### ISSUE THREAD

**Issue by p-linnane** [alexei-led/pumba#233]
Hello 👋 . I'm a maintainer for the [Homebrew](https://brew.sh) project. While packaging pumba 0.9.6 we noticed that running `pumba --version` no longer returns the version. This is the current output in 0.9.6:

```
pumba --version
Pumba version local - [none:none] none
```

Please advise if this is expected behavior. Thanks!

**Comment by alexei-led** [comment]
fixed
