### ISSUE TITLE
pumba need support for docker log driver

### ISSUE THREAD

**Issue by thatsk** [alexei-led/pumba#236]

**Comment by alexei-led** [comment]
@thatsk Please provide more details. What is missing in current logs?

**Comment by thatsk** [comment]
as my docker daemon running with log driver so when I am running pumba with container on node it give me following error:- 
```
docker run -it --log-driver=fluentd --log-opt fluentd-address=nodename:24224  --rm  -v /var/run/docker.sock:/var/run/docker.sock  gaiaadm/pumba --interval=60s  --random --log-level=info  stress -d 10m  're2:^containername'
INFO[0000] stress testing container                      dryrun=false duration=10m0s id=07ad2f4e773fa9a0577912e11094dbb404c1fb248be1460643a7bbb300b52238 image="alexeiled/stress-ng:latest-ubuntu" name=/containername-5b14bf22-f735-4670-6154-de58503e6f99 pull=true stressors="[--cpu 4 --timeout 60s]"
FATA[0002] error running stress command: error running chaos command: one or more stress test failed: stress test failed: failed to start stress-ng container: Error response from daemon: failed to initialize logging driver: dial tcp 0.0.0.0:24224: connect: connection refused 
```

**Comment by thatsk** [comment]
am i missing something @alexei-led

**Comment by thatsk** [comment]
this is docker daemon configuration on node.
```
OPTIONS=" -H unix:///var/run/docker.sock --ip-forward=true --iptables=true --ip-masq=true -G docker --label stage=farm --metrics-addr=10.174.26.109:9323 --experimental=true --log-driver=fluentd --log-opt fluentd-address=0.0.0.0:24224 "
```

**Comment by alexei-led** [comment]
If you already configured Docker daemon with fluentd log driver, there is no need to specify the log driver at the container level. Just run `pumba` container without `--log-driver` and `--log-opt` flags.

**Comment by thatsk** [comment]
```
docker run   --rm  -v /var/run/docker.sock:/var/run/docker.sock  gaiaadm/pumba --interval=60s  --random --log-level=info  stress -d 10m  're2:^containername'
```
Output:-

docker: Error response from daemon: failed to initialize logging driver: dial tcp 0.0.0.0:24224: connect: connection refused.

**Comment by thatsk** [comment]
i tried that and getting this and even pumba is not initializing

**Comment by alexei-led** [comment]
Besides that your Docker daemon configuration for fluentd is wrong: you need to specify a valid Fluentd address. `0.0.0.0` is not a valid address. You need to specify IP of Fluentd server here

**Comment by alexei-led** [comment]
You will get the same error for any Docker container that prints anything on stdout/stderr

**Comment by alexei-led** [comment]
Not pumba specific error. Closing it. Please read the documentation https://docs.docker.com/config/containers/logging/fluentd/

**Comment by thatsk** [comment]
i am defining on 0.0.0.0:2424 to listen on all IP address which is working fine and you are saying you can run fluentd address to specific address ? something like eth0 not to listen on all IP configured for that machine

**Comment by thatsk** [comment]
@alexei-led thanks for your info.
