### ISSUE TITLE
docker_entrypoint.sh changes ownership of parent socket

### ISSUE THREAD

**Issue by jmmclean** [alexei-led/pumba#38]
When running a command similar to the below, the parent docker.sock will change its ownership based on the container `chown` command.

`sudo docker run -v /var/run/docker.sock:/var/run/docker.sock:ro --name pumba-netem-delay-2000 gaiaadm/pumba pumba netem --duration 1m delay --time 2000  <container_name>`

ownership of docker.sock will become 1000:1000 (since pumba user/group likely unknown to docker engine)

**Comment by slnowak** [comment]
@alexei-led 
what is the reason for running pumba as pumba:pumba user instead of root:root? 
I had issues running pumba container on travis because of that.

Is there any reason we can't have entrypoint that looks like the following:

> #!/bin/sh
> set -e
> exec gosu root:root "$@"
(or replace gosu with su-exec)?

**Comment by alexei-led** [comment]
Fixed this issue, try latest `gaiaadm/pumba:latest`. should work now.
