### ISSUE TITLE
No such image: gaiadocker/iproute2

### ISSUE THREAD

**Issue by Tyson1986** [alexei-led/pumba#40]
When you try to do for example:
pumba --debug netem --duration 2m --tc-image gaiadocker/iproute2 delay --time 10000 re2:^web
you will get 'Error: No such image: gaiadocker/iproute2' until you will do 'docker pull gaiadocker/iproute2'.
From local run it's ok. But if run it on Jenkins or inside docker (brand new OS\container\etc.) you should run 'docker pull gaiadocker/iproute2' before test run.
Can you provide docker pull if use '--tc-image gaiadocker/iproute2'  ?

**Comment by alexei-led** [comment]
OK, I see, the issue.
Currently, you need to have any `tc` image (where `tc` is an entry point) near to `pumba`. 
I can change `pumba` to pull image, but it won't work with private images (or will need to add credentials too).
Anyway, will try to do something soon. Meanwhile "preload" image on Jenkins server

**Comment by Tyson1986** [comment]
Yes, i do docker pull before run, so this isn't big problem. But as a enhancement will be good.
