### ISSUE TITLE
Better killing and respawing options 

### ISSUE THREAD

**Issue by amarouni** [alexei-led/pumba#46]
It would be very helpful if the kill command, when passed a list of containers to kill, can kill a certain number of containers and keep the rest of the containers running.

Another option that goes with the above one, is the possibility to respawn killed containers.

Both of the options can be used together to randomly kill and respawn containers for a full chaos monkey experience !

**Comment by alexei-led** [comment]
seems like a good idea

**Comment by alexei-led** [comment]
Closing issue, since it's resolved: can limit number of container to kill.

**Comment by alexei-led** [comment]
Fixed.
