### ISSUE TITLE
Kubernetes Chaos Test

### ISSUE THREAD

**Issue by alexei-led** [alexei-led/pumba#51]
Add Kubernetes specific Chaos actions:
1. Kill Pod
2. Drain Node
3. Invoke "classic" Pumba on "selected" (by K8s selector) nodes
4. Other ideas?

**Comment by Lawouach** [comment]
Things that would be neat, specially if you open up an API (#75), is the capability of filtering what pods to target by label :)

**Comment by Dieterbe** [comment]
one concern i have with pumba is that some of its abstractions get really thin.
like for example, killing a pod is trivial to do with kubectl. why need pumba? if pumba adds all kinds of scheduling/selection/etc mechanisms then it becomes interesting.

**Comment by alexei-led** [comment]
Another approach would be to create **Chaos** CRD resource and run `pumba` as Kubernetes controller, watching for **Chaos** resource creation to start chaos, then update resource status and at the end cleanup everything.

**Comment by alexei-led** [comment]
working on Pumba K8s operator in another repo

**Comment by aayoubi** [comment]
hello @alexei-led , which is repo is that? 🙌🏼
