### ISSUE TITLE
Add Start command.

### ISSUE THREAD

**Issue by Tyson1986** [alexei-led/pumba#59]
In my tests i use Docker directly for stop/start containers. Test case is:
1. Stop container
2. Check system behavior
3. Start the same container
4. Check
5. Stop next container
.......

Also sometimes i want to start new instance of some service, or the same. In this case pause isn't good. Stop by Pumba and start by Docker CLI looks weird.
@alexei-led does it make sense?

**Comment by alexei-led** [comment]
@Tyson1986 so, you want Stop and Restart after a while, right? If this is the case, IMHO, it looks reasonable. Will mark this issue as an enhancement. Will gladly accept PR too!

**Comment by alexei-led** [comment]
I've added `--restart` option (and `--duration` for restart) to the `stop` command. Should help to resolve this issue.
