### ISSUE TITLE
Pumba container exiting without any error

### ISSUE THREAD

**Issue by vedantt** [alexei-led/pumba#70]
I am trying to setup Pumba on my docker swarm setup. I tried using the docker service create, docker stack deploy and a simple docker run command with following parameters

docker run -d -v /var/run/docker.sock:/var/run/docker.sock gaiaadm/pumba:master Pumba kill --signal SIGTERM

docker service create --constraint 'node.role == manager' --mount type=bind,source=/var/run/docker.sock,destination=/var/run/docker.sock gaiaadm/pumba:master --with-registry-auth

docker yml compose - file content
```
version:"3.4"
services:
pumba: image: gaiaadm/pumba:latest
volumes:
- /var/run/docker.sock:/var/run/docker.sock
deploy:
replicas: 3
command: ["pumba", "kill","re2:^customer-api*","--signal", `"SIGTERM"]` 
```

and created the above compose file for stack deploy.
But in all the cases the Pumba container just kills the mentioned container as customer-api* in compose file above and exits and restarts due to swarm maintaining state feature
I need the container to keep running.
I am new to docker and Pumba any help or direction will be really appreciated
Thanks in advance.

**Comment by alexei-led** [comment]
`pumba` `kill` command kills container and exits. No error, if it succeeded to do so or there is no container to kill. Pumba will exit with an error if it will fail to connect to Docker host, or has no permission to perform chaos action or something bad happens. This is by design.
