### ISSUE TITLE
Is there a Pumba API?

### ISSUE THREAD

**Issue by ratripathi** [alexei-led/pumba#75]
Is there a Pumba API available.
Scenario:

1) Install Pumba on the docker machine
2)Using API I want to interact with that machine to execute the Resiliency scenarios?

**Comment by alexei-led** [comment]
@rahulqelfo No API yet, just CLI
I'm thinking to add a "server" mode, where you could interact with already running pumba instance.

**Comment by Dieterbe** [comment]
I think pumba being a stateful server, controlled via an api, is a better model than the current imperative model.
For comparison, https://github.com/shopify/toxiproxy uses this model effectively. And the source is elegant too.  Perhaps some of that code can be reused here.

Unfortunately, it's been about a year since i built a pumba based chaos testing kit for my application, so I can't quite articulate the reasoning and trade-offs as well as I did before.

**Comment by sezhiyant** [comment]
Hi Alexei,

Any update on adding API support ?

Thanks,
Sezhiyan

**Comment by alexei-led** [comment]
@sezhiyant I thought about adding API, even started a new development in a separate bunch.
But, after a while, I did not find a real use case for the API.
In general, you should run `pumba` on every Docker host (or K8s node) where you would like to inject a failure. There is no single `pumba` server, but multiple distributed instances running on different hosts. If you want to inject specific error/s just deploy `pumba` with corresponding arguments on desired host/s. Once you are done, delete this deployment. You can run multiple instances on the same host running different commands.
So, what is the case for API? Deploy - to start chaos test; remove deployment - once you've done.

**Comment by sezhiyant** [comment]
Thanks for the response Alexei.

My use case - We use Kubernetes for the deployment of the services. I want to give the possibility of configuring, scheduling and running the Chaos scenarios to my customer ( Development team ). For this i have developed and deployed an API service. This service should be able to trigger the Chaos scenarios as and when needed.
I thought deploying pumba for every trigger of a Chaos would be an overkill, which could be simplified by the APIs if supported by pumba. For now, i plan to deploy another service along with pumba on every node, which will just receive the Chaos trigger and invoke the pumba CLI command. Additionally whenever these nodes come up, they will register themselves to the main scheduler service.

I would like to hear your views on this ?

**Comment by alexei-led** [comment]
Hi @sezhiyant 

I also thought about similar use case, but came to conclusion that it’s easier to use K8s API for this use case. Maybe, some day, I will add K8s CRD, but this has also its price (learning new syntax)
As for today, using DaemonSet, is the recommended way. Just prepare a pumba DaemonSet (multiple pumba containers can be included into the same DaemonSet). Deploy it to start chaos, remove to stop.
There is an example yaml in the repository
