### ISSUE TITLE
Got permission denied after using pumba to delay network

### ISSUE THREAD

**Issue by robooo** [alexei-led/pumba#83]
I built pumba using Docker master branch

I have few services running in a docker swarm and running new ones with 
`--network=host` flag. (I need it for testing purpose and can't simulate `docker network disconnect` with this flag).

After service is running I need to simulate disconnect from network, later packet loss etc...

I ran 
`docker run -v /var/run/docker.sock:/var/run/docker.sock -ti pumba pumba netem --duration 10s delay -t 10000 ${container_id}`  
after this when I want to run some docker command I get:

```
docker ps -a
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.32/containers/json?all=1: dial unix /var/run/docker.sock: connect: permission denied
```

only restart of docker help.

Is my scenario correct or miss I something? or is this issue?

**Comment by alexei-led** [comment]
@robooo I will try to reproduce this issue and fix it. thank you

**Comment by robooo** [comment]
Sorry I can't share our deploy scripts, but you can find some docker swarm solution composed of micro services allow them use to host network, spin up new container or stack with `--network=host` flag (maybe this is optional) and then as I mentioned before, run pumba and try docker commands

**Comment by alexei-led** [comment]
ok, will check this

**Comment by alexei-led** [comment]
fixed this issue. I do not modify `/var/run/docker.sock` owner, but add container user to the group that owns Docker socket. Should work now. Try and let me know.

Thank you for reporting this issue.

**Comment by robooo** [comment]
now I get

```
currently uid=0(root) gid=0(root) groups=0(root),1(bin),2(daemon),3(sys),4(adm),6(disk),10(wheel),11(floppy),20(dialout),26(tape),27(video) switch to 9001
adding pumba use for uid 9001
adding 999 to group docker
WARN[0000] no containers to found                        app=pumba function=github.com/alexei-led/pumba/pkg/chaos/netem.(*DelayCommand).Run source=netem/delay.go:144
```
what I miss there?

**Comment by robooo** [comment]
@alexei-led

**Comment by alexei-led** [comment]
run `pumba netem --help`

`pumba` uses `tc` tool for traffic shaping. If the container has this tool onboard than it will work, otherwise use "side-loaded" container with help of `--tc-image` option (you can use container I've prepared `gaiadocker/iproute2` or create your own container with `tc` installed)

*fixed command* would be: 
 ```
docker run -v /var/run/docker.sock:/var/run/docker.sock -ti pumba pumba netem --tc-image gaiadocker/iproute2  --duration 10s delay -t 10000 ${container_name}
```

**Comment by robooo** [comment]
this is help:
```
docker run -v /var/run/docker.sock:/var/run/docker.sock --network=host -ti pumba pumba --help
currently uid=0(root) gid=0(root) groups=0(root),1(bin),2(daemon),3(sys),4(adm),6(disk),10(wheel),11(floppy),20(dialout),26(tape),27(video) switch to 9001
adding pumba use for uid 9001
adding 999 to group docker
NAME:
   Pumba - Pumba is a resilience testing tool, that helps applications tolerate random Docker container failures: process, network and performance.

USAGE:
   pumba [global options] command [command options] containers (name, list of names, or RE2 regex if prefixed with "re2:")
   
VERSION:
   0.5.0 - 0f79dc2 (master) 2018-07-23_07:26_GMT
   
AUTHOR(S):
   Alexei Ledenev <alexei.led@gmail.com> 
   
COMMANDS:
     kill     kill specified containers
     stop     stop containers
     pause    pause all processes
     rm       remove containers
     netem    emulate the properties of wide area networks
     help, h  Shows a list of commands or help for one command

GLOBAL OPTIONS:
   --host value, -H value       daemon socket to connect to (default: "unix:///var/run/docker.sock") [$DOCKER_HOST]
....
```

**Comment by robooo** [comment]
it works now (when I set interface to docker, hope it's correct) but I'm getting strange issue, connection during the netem delay is Online but after the timeout my other containers go offline :) but that will be issue at my side.
Thank you!
