### ISSUE TITLE
cat: can't open 'VERSION': No such file or directory

### ISSUE THREAD

**Issue by venkiradkris** [alexei-led/pumba#87]
Hi - I am trying to install Pumba as a container in a Docker. While i am executing below command, i am getting error. Please help/suggest.  Thanks.

Command: 
"docker build -t pumba -f Dockerfile ."

Error: 
Step 10/25 : RUN if [[ "$RELEASE" == false ]]; then VERSION=$(cat VERSION) hack/test.sh; fi
 ---> Running in 01fa9e3878dc
cat: can't open 'VERSION': No such file or directory
/bin/sh: hack/test.sh: not found
The command '/bin/sh -c if [[ "$RELEASE" == false ]]; then VERSION=$(cat VERSION) hack/test.sh; fi' returned a non-zero code: 127

Regards
Venkat

**Comment by alexei-led** [comment]
hi @venkiradkris you are running build command in wrong directory
ruin it in project root, or use `hack\build.sh`

**Comment by venkiradkris** [comment]
Thanks.
