### ISSUE TITLE
Pumba run time startup issues

### ISSUE THREAD

**Issue by venkiradkris** [alexei-led/pumba#88]
Hi - Please help/suggest. Thanks.

Case [1] - Pumba running in Machine A and Docker Running in Machine B (10.180.218.245)

I am not able to connect Docker running in Machine B with Pumba running as standalone (i.e NOT IN DOCKER) in Machine A.

Command: pumba --host 10.180.218.245
Issue: FATA[0000] Error instantiating Docker engine-api: unable to parse docker host `10.180.218.245`  app=pumba function=github.com/alexei-led/pumba/pkg/container.NewClient source=container/client.go:54

Case [2] - Pumba Image installed in a Docker. 

I have installed Tomcat image inside Docker. Tomcat container is up and running. I am not able to execute below basic command.

Command: sudo docker run pumba --interval 1m kill --signal SIGTERM tomcat &
Issue:  /docker_entrypoint.sh: exec: line 22: illegal option --

Regards
Venkat

**Comment by alexei-led** [comment]
@venkiradkris 

For case [1], please make sure you can access `docker daemon` on Machine B from Machine A with `docker --host=10.180.218.245 info`. If you cannot connect with `docker` client, you need to configure daemon to work over TCP and allow access from Machine A (preferably with `TLS` certificates)

As for case [2] you need to provide `pumba` a way it can talk to the docker daemon, mounting `/var/run/docker.sock` or specifying `--host` and `--tls*` (certificates). First, try to run `pumba` as app (not in docker) and then run it in docker container. 

p.s.: next time please create two separate issues
