### ISSUE TITLE
Pumba Commands for chaos testing

### ISSUE THREAD

**Issue by venkiradkris** [alexei-led/pumba#89]
Hi - I have got following chaos testing test scenarios. 

1. Impact of lack of logging space on the microservices/containers (simulate the Docker container 'Cannot write: No space left on device' error) or set '--storage-opt size=X'. Observe effects on other services

2. Lack of space on Docker volumes (Should configure existing docker containers with startup parameters to simulate the chaos conditions)

3. Simulate a CPU usage of say 80% for 10 minutes every hour and observe the behaviour of the system. 

4. Loss of connectivity with 3rd party dependency services

Please suggest / give me some lead to derive pumba commands for testing.

Regards
Venkat

**Comment by alexei-led** [comment]
@venkiradkris currently these things are not possible. Agree with you that these are interesting use cases. I thought to use an injected container with `stress-ng` tool on board to achieve this. 
I will publish project roadmap and will include this request there. Not sure when it will be done, but can accept PR too.

**Comment by venkiradkris** [comment]
Thanks a lot for your update/response.

Do you have any tool suggestion for executing above test cases specifically for Docker Containers/Micro Services? Kindly update.

Regards
Venkat

**Comment by alexei-led** [comment]
`stress` command is available now
