### ISSUE TITLE
Pumba attack - visualize the execution steps in command terminal 

### ISSUE THREAD

**Issue by venkiradkris** [alexei-led/pumba#91]
Hi

If i am executing below docker attack commands, is there any way to visualize the attack/execution step/step? I am using command/terminal window with "watch docker ps -n 50".

pumba netem delay
pumba netem loss

Is there any way? Even in zabbix, i am not able to visualize the attack. Please suggest.

Regards
Venkat

**Comment by alexei-led** [comment]
If you want to see the delay, use monitoring tools. To see `pumba` activity use `--debug` flag.

p.s.: consider using for questions Gitter https://gitter.im/pumba-chaos/Lobby?source=orgpage instead of GitHub issues.

**Comment by venkiradkris** [comment]
Hi 

I have used below command with "--debug"
pumba_linux_amd64 pause --duration 10s assetclass --debug

I am not getting execution output in command prompt/terminal. Am i missing anything here?

Regards
Venkat

**Comment by alexei-led** [comment]
Sorry, my mistake, this option had been changed.
Use `--log-level=debug`.

Ru  `pumba --help` to see all options and commands.
