### ISSUE TITLE
Problem with list of IPs

### ISSUE THREAD

**Issue by Tyson1986** [alexei-led/pumba#92]
Regarding to new functionality (https://github.com/alexei-led/pumba/issues/57) i'm trying to provide list of IP addresses. But i failed. I've tried:
--target 172.29.0.6, 172.29.0.10
--target 172.29.0.6,172.29.0.10
--target 172.29.0.6, --target 172.29.0.10
--target [172.29.0.6, 172.29.0.10]
--target "172.29.0.6","172.29.0.10"
--target "172.29.0.6,172.29.0.10"
--target "172.29.0.6, 172.29.0.10"
README doesn't provide any example.

**Comment by alexei-led** [comment]
will take a look

**Comment by kunal-bhatia** [comment]
+1

**Comment by ddliu** [comment]
Same problem here, but following works for me:

```
--target=172.29.0.6 --target=172.29.0.10
```

**Comment by lazerion** [comment]
+1

**Comment by alexei-led** [comment]
need to pass with multiple separate target flag; comma separated list is not supported
