### ISSUE TITLE
Add SVG version of Pumba logo

### ISSUE THREAD

**Issue by caniszczyk** [alexei-led/pumba#94]
For the CNCF Landscape (l.cncf.io), we need an SVG version of the logo.

Can you add it to the repo somewhere :)?

**Comment by alexei-led** [comment]
@caniszczyk I've tried to do something, take a look at [this](
https://github.com/alexei-led/pumba/raw/master/docs/img/pumba_logo.svg). I'm not an artist, so this is my best effort.
